config/routes.rb
BuildScaffold2::Application.routes.draw do

  devise_for :users
  get '/exams' => "exams#home", as: 'exams'
  post '/exams' => "exams#create"
  get '/exams/new' => "exams#new", as: 'new_exam'
  get '/exams/:id/edit' => "exams#edit", as: 'edit_exam'
  get '/exams/:id' => "exams#show", as: 'exam' 
  patch '/exams/:id' => "exams#update"
  put '/exams/:id' => "exams#update"
  delete '/exams/:id' => "exams#destroy"

  root :to => "exams#home"

    
 

end

app/models/exam.rb
class Exam < ActiveRecord::Base

validates_presence_of :name, :marks, :message => "can't be blank"
validates_numericality_of :marks, :message => "must be number"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
	before_filter :authenticate_user!
	before_action :set_exam, only: [:show, :edit, :update, :destroy]

	def home
		@exam = Exam.all
	end
	def index
		@exam = Exam.all
	end

	def new
		@exam = Exam.new
	end

	def create
		@exam = Exam.new(exam_params)

		if @exam.save
		redirect_to exams_path
		else 
		render 'new'
		end
	end

	def edit
		
	end

	def update
		if @exam.update_attributes(exam_params)
		redirect_to exams_path
		else 
		render 'edit'
		end
		
	end

	def show
		
	end

	def destroy
		@exam.destroy
		redirect_to exams_path
	end

	def set_exam
		@exam = Exam.find(params[:id])
	end
	def exam_params
		params.require(:exam).permit(:name, :marks)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_error.html.erb
<% if @exam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ol>
    <% @exam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
    
  </div>
  
<% end %>




<%= form_for @exam do |f| %>
	<%= f.label :name %></br>
	<%= f.text_field :name %></br></br>
	<%= f.label :marks %></br>
	<%= f.text_field :marks %></br>
	<%= f.submit  %>

<% end %>

app/views/exams/edit.html.erb
<%= render 'error' %>

<%= link_to 'Back', exams_path %>

app/views/exams/home.html.erb
<h1>Exam Results:</h1>
<table>
	<thead>
		<tr>
			<th>Student Name |</th>
			<th>| Marks secured</th>
			<th></th>
			<th></th>
			<th></th>

		</tr>
	</thead>
	<tbody>
		<% @exam.each do |f| %>
			<tr>
				<td><%= f.name %></td>
				<td><%= f.marks %></td>
				<td><%= link_to 'Show', exam_path(f) %></td>
				<td><%= link_to 'Edit', edit_exam_path(f) %></td>
				<td><%= link_to 'Destroy', f , method: :delete, data: {confirm: 'Do You really want to delete this entry?' } %></td>
				
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Student', new_exam_path %>

app/views/exams/index.html.erb
<h1>Exam Results:</h1>
<table>
	<thead>
		<tr>
			<th>Student Name |</th>
			<th>| Marks secured</th>
			<th></th>
			<th></th>
			<th></th>

		</tr>
	</thead>
	<tbody>
		<% @exam.each do |f| %>
			<tr>
				<td><%= f.name %></td>
				<td><%= f.marks %></td>
				<td><%= link_to 'Show', f %></td>
				<td><%= link_to 'Edit', edit_exam_path(f) %></td>
				<td><%= link_to 'Destroy', f , method: :delete, data: { confirm: 'Do You really want to delete this entry?' } %></td>
				
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Student', new_exam_path %>

app/views/exams/new.html.erb
<%= render 'error' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p>Name: <%= @exam.name %></p>
<p>Name: <%= @exam.marks %></p>

<%= link_to 'Back', exams_path %>
<%= link_to 'Edit', edit_exam_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuildScaffold2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>



 <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>



<%= yield %>

</body>
</html>